import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const here = path.dirname(new URL(import.meta.url).pathname);
const componentPath = path.join(here, "AgentChatWorkspace.tsx");

describe("AgentChatWorkspace", () => {
  it("is a standalone agent-chat UI and never sends its draft to a terminal", () => {
    expect(existsSync(componentPath)).toBe(true);
    const source = readFileSync(componentPath, "utf8");

    expect(source).toContain("Start a {agent.name} session");
    expect(source).toContain("active: boolean");
    expect(source).toContain("chatId: string");
    expect(source).toContain("flex h-10 shrink-0 items-center border-b");
    expect(source).toContain("if (!active || modelsRequestedRef.current || modelsLoading) return;");
    expect(source).toContain("void refreshModels();");
    expect(source).toContain("onOpen={loadControlsOnDemand}");
    expect(source).toContain("Session ID pending");
    expect(source).not.toContain("Chat settings");
    expect(source).not.toContain("Settings02Icon");
    expect(source).not.toContain("workspaceName");
    expect(source).not.toContain("{agent.name}</span>");
    expect(source).toContain("Message the agent");
    expect(source).toContain("/commands and /skills");
    expect(source).toContain("useAgentChatSession");
    expect(source).toContain('<AgentStateDot state="working" />');
    expect(source).toContain("provider");
    expect(source).toContain("ChatOutlineRail");
    expect(source).toContain("onMouseEnter");
    expect(source).toContain("Chat outline");
    expect(source).toContain("responseOutlineItems");
    expect(source).not.toContain("length: 64");
    expect(source).toContain("MAX_OUTLINE_LINES = 80");
    expect(source).toContain("outlineWindow");
    expect(source).toContain("const slotHeight");
    expect(source.indexOf("<ChatOutlineRail")).toBeLessThan(source.indexOf("ref={scrollRef}"));
    expect(source).not.toContain('z-10 hidden lg:block');
    expect(source).not.toContain("<aside");
    expect(source).not.toContain("Search history...");
    expect(source).toContain("selectedModel");
    expect(source).toContain("Upload file");
    expect(source).toContain("Add attachment");
    expect(source).toContain("Attach URL");
    expect(source).toContain("file.text()");
    expect(source).toContain("URL.createObjectURL");
    expect(source).toContain("Image attachment selected");
    expect(source).toContain("AiChat01Icon");
    expect(source).toContain("Attached context:");
    expect(source).toContain("Search models...");
    expect(source).toContain("Discovered");
    expect(source).toContain("Refresh models");
    expect(source).not.toContain("Create profile");
    expect(source).not.toContain("Diagnostic");
    expect(source).not.toContain("MODEL_DESCRIPTIONS");
    expect(source).not.toContain("FALLBACK_MODEL_IDS");
    expect(source).toContain("listAgentChatModels");
    expect(source).toContain("listAgentChatSlashOptions");
    expect(source).toContain("/effort");
    expect(source).toContain("/mode");
    expect(source).toContain("Toggle fast mode");
    expect(source).toContain("setSelectedModel((current) => current || normalized[0]?.id || \"\")");
    expect(source).toContain("Loading models from");
    expect(source).toContain("Default model");
    expect(source).toContain("loadAgentChatConfig(chatId)");
    expect(source).toContain("loadAgentModelCache(provider)");
    expect(source).toContain("saveAgentModelCache");
    expect(source).toContain("needsCliDefaults");
    expect(source).toContain("applyControlOptions(options, config ?? {})");
    expect(source).not.toContain("AGENT_OPTIONS");
    expect(source).not.toContain("readOnly");
    expect(source).not.toContain("onSend");
    expect(source).not.toContain("Sent to");
    expect(source).not.toContain("CmdInteractiveAgentChat");
    expect(source).not.toContain("TerminalPane");
  });

  it("keeps context usage and dictation local to the agent-chat composer", () => {
    const source = readFileSync(componentPath, "utf8");

    expect(source).toContain("getAgentUsageStatuses(cwd, provider, timeline.nativeSessionId)");
    expect(source).toContain("timeline.status]);");
    expect(source).toContain("ContextWindowMeter");
    expect(source).toContain("Context window unavailable from this CLI");
    expect(source).toContain("TooltipContent side=\"top\"");
    expect(source).toContain("% used");
    expect(source).toContain("useWhisperRecording");
    expect(source).toContain("terminalFontFamily");
    expect(source).toContain("terminalFontSize");
    expect(source).toContain("terminalLetterSpacing");
    expect(source).toContain("chatTextStyle");
    expect(source).toContain("Voice to text");
    expect(source).toContain("Confirm voice transcript");
    expect(source).toContain("Cancel voice transcript");
    expect(source).toContain("Steer agent with this prompt");
    expect(source).toContain('timeline.status === "running" ? steer : submit');
    expect(source).toContain("voiceRecorder.duration");
    expect(source).toContain("setDraft((current) =>");
    expect(source).toContain("audioLevel");
    expect(source).not.toContain("<VoiceLevelMeter audioLevel={0} active={false} />");
    expect(source).toContain("AssistantResponseActions");
    expect(source).toContain("buildAgentChatForkHistory");
    expect(source).toContain("Chat history attachment:");
    expect(source).toContain("historyAttachments");
    expect(source).toContain("Copy response");
    expect(source).toContain("Copy prompt");
    expect(source).toContain("Edit prompt");
    expect(source).toContain("rewriteFromPrompt");
    expect(source).toContain("Fork in a new tab");
    expect(source).toContain("Fork in a new workspace");
    expect(source).toContain("formatWorkedDuration");
    expect(source).toContain("Worked for {formatWorkedDuration(workedMs)}");
    expect(source).toContain("absolute bottom-4 left-1/2 z-20");
    expect(source).not.toContain("void send(transcript)");
  });

  it("surfaces agent-edited files as a reviewable card at the end of the timeline", () => {
    const source = readFileSync(componentPath, "utf8");

    expect(source).toContain("AgentEditCard");
    expect(source).toContain("Edited {files.length}");
    expect(source).toContain("onReview={reviewEdits}");
    expect(source).toContain("onUndo={() => void undoEdits()}");
    expect(source).toContain("native.gitPanelSnapshot(cwd)");
    expect(source).toContain("native.gitDiff");
    expect(source).toContain("native.gitDiscard");
    expect(source).toContain("onOpenFileDiff");
  });
});
