import {
  ApiIcon,
  ArrowRight01Icon,
  ArtificialIntelligence04Icon,
  BoundingBoxIcon,
  CircleIcon,
  CloudIcon,
  DatabaseIcon,
  DatabaseSyncIcon,
  DeliveryBox01Icon,
  HashtagIcon,
  ImageAdd01Icon,
  LineIcon,
  PackageIcon,
  PencilEdit01Icon,
  Queue01Icon,
  Router01Icon,
  ServerStackIcon,
  Shield01Icon,
  SquareIcon,
  TextIcon,
  TerminalIcon,
  UserIcon,
  WorkflowSquare01Icon,
} from "@hugeicons/core-free-icons";
import type { ShapeConfig, ShapeKind } from "./architectureCanvasTypes";

export const ARCHITECTURE_SHAPES: ShapeConfig[] = [
  {
    kind: "rectangle",
    label: "Rectangle",
    category: "Drawing",
    description: "Generic shape, box, note, or container",
    icon: SquareIcon,
    mode: "rectangle",
    tone: "border-zinc-400/35 bg-zinc-500/[0.08] text-zinc-700 dark:text-zinc-200",
  },
  {
    kind: "circle",
    label: "Circle",
    category: "Drawing",
    description: "Round node, state, or compact concept",
    icon: CircleIcon,
    mode: "circle",
    tone: "border-slate-400/35 bg-slate-500/[0.08] text-slate-700 dark:text-slate-200",
  },
  {
    kind: "frame",
    label: "Frame",
    category: "Drawing",
    description: "# frame for grouping areas",
    icon: HashtagIcon,
    mode: "frame",
    tone: "border-neutral-400/35 bg-neutral-500/[0.08] text-neutral-700 dark:text-neutral-200",
  },
  {
    kind: "text",
    label: "Text",
    category: "Drawing",
    description: "T label or annotation",
    icon: TextIcon,
    mode: "text",
    tone: "border-teal-400/35 bg-teal-500/[0.08] text-teal-700 dark:text-teal-200",
  },
  {
    kind: "image",
    label: "Image",
    category: "Drawing",
    description: "Image placeholder with URL or upload",
    icon: ImageAdd01Icon,
    mode: "image",
    tone: "border-pink-400/35 bg-pink-500/[0.08] text-pink-700 dark:text-pink-200",
  },
  {
    kind: "terminal",
    label: "Terminal",
    category: "Platform",
    description: "Independent shell on the canvas",
    icon: TerminalIcon,
    tone: "border-emerald-400/35 bg-emerald-500/[0.08] text-emerald-700 dark:text-emerald-200",
  },
  {
    kind: "line",
    label: "Line",
    category: "Drawing",
    description: "Free line between points",
    icon: LineIcon,
    mode: "line",
    tone: "border-gray-400/35 bg-gray-500/[0.08] text-gray-700 dark:text-gray-200",
  },
  {
    kind: "arrow",
    label: "Arrow",
    category: "Drawing",
    description: "Directional arrow",
    icon: ArrowRight01Icon,
    mode: "arrow",
    tone: "border-blue-400/35 bg-blue-500/[0.08] text-blue-700 dark:text-blue-200",
  },
  {
    kind: "pen",
    label: "Pen",
    category: "Drawing",
    description: "Freehand drawing",
    icon: PencilEdit01Icon,
    mode: "pen",
    tone: "border-cyan-400/35 bg-cyan-500/[0.08] text-cyan-700 dark:text-cyan-200",
  },
  {
    kind: "actor",
    label: "Actor",
    category: "C4",
    description: "User, team, client, or system persona",
    icon: UserIcon,
    tone: "border-rose-400/35 bg-rose-500/[0.08] text-rose-700 dark:text-rose-200",
  },
  {
    kind: "external",
    label: "External",
    category: "C4",
    description: "Third-party SaaS, partner, or dependency",
    icon: CloudIcon,
    tone: "border-violet-400/35 bg-violet-500/[0.08] text-violet-700 dark:text-violet-200",
  },
  {
    kind: "boundary",
    label: "Boundary",
    category: "C4",
    description: "System, team, zone, or trust boundary",
    icon: BoundingBoxIcon,
    tone: "border-stone-400/35 bg-stone-500/[0.08] text-stone-700 dark:text-stone-200",
  },
  {
    kind: "service",
    label: "Service",
    category: "Application",
    description: "App, backend service, or bounded context",
    icon: WorkflowSquare01Icon,
    tone: "border-sky-400/35 bg-sky-500/[0.08] text-sky-700 dark:text-sky-200",
  },
  {
    kind: "api",
    label: "API",
    category: "Application",
    description: "REST, GraphQL, RPC, or public interface",
    icon: ApiIcon,
    tone: "border-cyan-400/35 bg-cyan-500/[0.08] text-cyan-700 dark:text-cyan-200",
  },
  {
    kind: "worker",
    label: "Worker",
    category: "Application",
    description: "Job processor, consumer, scheduler",
    icon: ServerStackIcon,
    tone: "border-indigo-400/35 bg-indigo-500/[0.08] text-indigo-700 dark:text-indigo-200",
  },
  {
    kind: "function",
    label: "Function",
    category: "Application",
    description: "Serverless function or task handler",
    icon: PackageIcon,
    tone: "border-fuchsia-400/35 bg-fuchsia-500/[0.08] text-fuchsia-700 dark:text-fuchsia-200",
  },
  {
    kind: "ai",
    label: "AI service",
    category: "Application",
    description: "LLM, embedding, agent, or model gateway",
    icon: ArtificialIntelligence04Icon,
    tone: "border-purple-400/35 bg-purple-500/[0.08] text-purple-700 dark:text-purple-200",
  },
  {
    kind: "database",
    label: "Database",
    category: "Data",
    description: "Persistent storage or read model",
    icon: DatabaseIcon,
    tone: "border-emerald-400/35 bg-emerald-500/[0.08] text-emerald-700 dark:text-emerald-200",
  },
  {
    kind: "cache",
    label: "Cache",
    category: "Data",
    description: "Redis, CDN cache, session cache",
    icon: DatabaseSyncIcon,
    tone: "border-lime-400/35 bg-lime-500/[0.08] text-lime-700 dark:text-lime-200",
  },
  {
    kind: "queue",
    label: "Queue",
    category: "Data",
    description: "Event bus, stream, broker, or job queue",
    icon: Queue01Icon,
    tone: "border-amber-400/35 bg-amber-500/[0.10] text-amber-700 dark:text-amber-200",
  },
  {
    kind: "storage",
    label: "Storage",
    category: "Data",
    description: "Blob, bucket, object storage, files",
    icon: DeliveryBox01Icon,
    tone: "border-orange-400/35 bg-orange-500/[0.08] text-orange-700 dark:text-orange-200",
  },
  {
    kind: "gateway",
    label: "Gateway",
    category: "Platform",
    description: "Load balancer, ingress, API gateway",
    icon: Router01Icon,
    tone: "border-blue-400/35 bg-blue-500/[0.08] text-blue-700 dark:text-blue-200",
  },
  {
    kind: "security",
    label: "Security",
    category: "Platform",
    description: "Auth, secrets, policy, trust control",
    icon: Shield01Icon,
    tone: "border-red-400/35 bg-red-500/[0.08] text-red-700 dark:text-red-200",
  },
];

export function shapeFor(kind: ShapeKind): ShapeConfig {
  return ARCHITECTURE_SHAPES.find((shape) => shape.kind === kind)!;
}
