#[macro_export]
macro_rules! cmdspace_commands {
    () => {
        tauri::generate_handler![
            // Agent usage
            agent_usage::agent_usage_statuses,
            agent_usage::provider_limit_status,
            agent_usage::provider_limit_statuses,
            // Structured CLI agent chat
            agent_chat::commands::agent_chat_start,
            agent_chat::commands::agent_chat_attach,
            agent_chat::commands::agent_chat_detach,
            agent_chat::commands::agent_chat_runtime_status,
            agent_chat::commands::agent_chat_send,
            agent_chat::commands::agent_chat_cancel,
            agent_chat::commands::agent_chat_close,
            agent_chat::commands::agent_chat_load_history,
            agent_chat::commands::agent_chat_list_models,
            agent_chat::commands::agent_chat_list_slash_options,
            // PTY
            pty::pty_open,
            pty::pty_write,
            pty::pty_trace_input,
            pty::pty_resize,
            pty::pty_close,
            pty::pty_register_metadata,
            pty::pty_list,
            pty::pty_available_shells,
            pty::check_agent_clis,
            pty::list_agent_sessions,
            // Filesystem
            fs::tree::list_subdirs,
            fs::tree::fs_read_dir,
            fs::file::fs_read_file,
            fs::file::fs_read_image,
            fs::file::fs_read_video,
            fs::file::fs_write_file,
            fs::file::fs_stat,
            fs::file::select_folder,
            fs::file::fs_canonicalize,
            fs::mutate::fs_create_file,
            fs::mutate::fs_create_dir,
            fs::mutate::fs_rename,
            fs::mutate::fs_import_paths,
            fs::mutate::fs_import_clipboard_file,
            fs::mutate::fs_clipboard_paths,
            fs::mutate::fs_delete,
            fs::mutate::fs_restore,
            fs::search::fs_search,
            fs::search::fs_list_files,
            fs::grep::fs_grep,
            fs::grep::fs_glob,
            // Git
            git::commands::git_resolve_repo,
            git::commands::git_panel_snapshot,
            git::commands::git_status,
            git::commands::git_diff,
            git::commands::git_diff_content,
            git::commands::git_stage,
            git::commands::git_unstage,
            git::commands::git_discard,
            git::commands::git_commit,
            git::commands::git_fetch,
            git::commands::git_pull_ff_only,
            git::commands::git_push,
            git::commands::git_log,
            git::commands::git_show_commit,
            git::commands::git_commit_files,
            git::commands::git_commit_file_diff,
            git::commands::git_remote_url,
            // Shell
            shell::shell_run_command,
            shell::shell_session_open,
            shell::shell_session_run,
            shell::shell_session_close,
            shell::shell_bg_spawn,
            shell::shell_bg_logs,
            shell::shell_bg_kill,
            shell::shell_bg_list,
            // Workspace
            workspace::wsl_list_distros,
            workspace::wsl_default_distro,
            workspace::wsl_home,
            workspace::workspace_authorize,
            workspace::workspace_current_dir,
            workspace::app_dev_repo_root,
            // Window surfaces
            app_exit::app_exit_flush_complete,
            window_commands::get_launch_dir,
            window_commands::open_settings_window,
            window_commands::hide_workspace_switcher,
            window_commands::open_workspace_from_tray,
            window_commands::set_desktop_blur,
            window_commands::set_webview_corner_radius,
            // Secrets
            secrets::secrets_get,
            secrets::secrets_set,
            secrets::secrets_delete,
            secrets::secrets_get_all,
            // Network / AI transport
            net::lm_ping,
            net::ai_http_request,
            net::ai_http_stream,
            // Music
            music::music_is_playing,
            music::install_music_cli_script,
            // Remote access
            remote::remote_access_status,
            remote::remote_access_start,
            remote::remote_access_stop,
            remote::remote_access_reset_password,
            remote::remote_device_pairing_start,
            remote::remote_device_list,
            remote::remote_device_revoke,
            // Speech
            speech::speech_supported_locales,
            speech::speech_start,
            speech::speech_stop,
            // Database / persistence
            db::db_list_workspaces,
            db::db_save_workspace,
            db::db_delete_workspace,
            db::db_reorder_workspaces,
            db::db_list_panes,
            db::db_save_pane,
            db::db_list_recent_workspaces,
            db::db_save_recent_workspace,
            db::db_load_workspace_setup_custom_command,
            db::db_save_workspace_setup_custom_command,
            db::db_load_agent_chat_config,
            db::db_save_agent_chat_config,
            db::db_load_agent_model_cache,
            db::db_save_agent_model_cache,
        ]
    };
}
